name: Appium Mobile Web EmuSim Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */3 * * *'
  push:
    paths:
      - 'src/test/java/com/saucelabs/yy/Tests/Appium/MobileWeb/EmulatorSimulator/**'
      - 'src/test/resources/Appium/AppiumMobileWebEmulatorSimulator.xml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install compile test -Dsurefire.suiteXmlFiles=./src/test/resources/Appium/AppiumMobileWebEmulatorSimulator.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -V
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BUILD_TAG: Mobile-Web-EmuSim-1.${{ github.run_number }}