name: Device Check Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --quiet clean install compile test -Dsurefire.suiteXmlFiles=./src/test/resources/Device_Check.xml
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BUILD_TAG: Device-Check-1.${{ github.run_number }}
      - name: Read devices.txt
        id: devices
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: tmp/devices.txt
        if: ${{ failure() }}
      - name: Echo devices.txt
        run: echo "${{ steps.devices.outputs.content }}"
        if: ${{ failure() }}