name: Sauce Orchestrate

on:
  workflow_dispatch:

jobs:

  orchestrated_eu:
    strategy:
      max-parallel: 1
      matrix:
        counter: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        resourceProfile: [ c1m1, c2m2, c3m3 ]
    name: Run Tests using Sauce Orchestrate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: saucelabs/saucectl-run-action@v3
        env:
          DOCKER_IMAGE: ${{ vars.DOCKER_USERNAME }}/sauce-orchestrate-demo:latest
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          RESOURCE_PROFILE: ${{ matrix.resourceProfile }}
        with:
          saucectl-version: latest
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          env: |
            BUILD_TAG=SO-Smoke-Tests-Benchmark-${{ matrix.counter }}-${{ matrix.resourceProfile }}
            REGION=EU
          region: eu-central-1