name: Selenium Web Full Regression Tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install compile test -Dsurefire.suiteXmlFiles=./src/test/resources/Selenium/Selenium_Web_Full_Regression_Tests.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -V
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BUILD_TAG: Regression-Tests-1.${{ github.run_number }}
          TAGS: Regression,Desktop_Web
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1