name: Upload My Demo App monthly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 */30 * *'

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  download_upload_app:
    runs-on: ubuntu-latest
    steps:
      - name: Download My Demo App 1.3.0 apk
        uses: wei/curl@v1.1.1
        with:
          args: -L -o MyRNDemoApp-1.3.0.apk https://github.com/sceiler/Java-TestNG-Appium-Selenium/releases/download/1.0.0/MyRNDemoApp-1.3.0.apk

      - name: Upload My Demo App 1.3.0 apk
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"MyRNDemoApp-1.3.0.apk"' --form 'name="MyRNDemoApp-1.3.0.apk"'

      - name: Download My Demo App 1.3.0 zip
        uses: wei/curl@v1.1.1
        with:
          args: -L -o MyRNDemoApp-1.3.0.zip https://github.com/sceiler/Java-TestNG-Appium-Selenium/releases/download/1.0.0/MyRNDemoApp-1.3.0.zip

      - name: Upload My Demo App 1.3.0 zip
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"MyRNDemoApp-1.3.0.zip"' --form 'name="MyRNDemoApp-1.3.0.zip"'

      - name: Download My Demo App 1.3.0 ipa
        uses: wei/curl@v1.1.1
        with:
          args: -L -o MyRNDemoApp-1.3.0.ipa https://github.com/sceiler/Java-TestNG-Appium-Selenium/releases/download/1.0.0/MyRNDemoApp-1.3.0.ipa

      - name: Upload My Demo App 1.3.0 ipa
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"MyRNDemoApp-1.3.0.ipa"' --form 'name="MyRNDemoApp-1.3.0.ipa"'

      - name: Download My Demo App 1.5.0 apk
        uses: wei/curl@v1.1.1
        with:
          args: -L -o MyRNDemoApp-1.5.0.apk https://github.com/sceiler/Java-TestNG-Appium-Selenium/releases/download/1.0.0/MyRNDemoApp-1.5.0.apk

      - name: Upload My Demo App 1.5.0 apk
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"MyRNDemoApp-1.5.0.apk"' --form 'name="MyRNDemoApp-1.5.0.apk"'

      - name: Download My Demo App 1.5.0 zip
        uses: wei/curl@v1.1.1
        with:
          args: -L -o MyRNDemoApp-1.5.0.zip https://github.com/sceiler/Java-TestNG-Appium-Selenium/releases/download/1.0.0/MyRNDemoApp-1.5.0.zip

      - name: Upload My Demo App 1.5.0 zip
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"MyRNDemoApp-1.5.0.zip"' --form 'name="MyRNDemoApp-1.5.0.zip"'

      - name: Download My Demo App 1.5.0 ipa
        uses: wei/curl@v1.1.1
        with:
          args: -L -o MyRNDemoApp-1.5.0.ipa https://github.com/sceiler/Java-TestNG-Appium-Selenium/releases/download/1.0.0/MyRNDemoApp-1.5.0.ipa

      - name: Upload My Demo App 1.5.0 ipa
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"MyRNDemoApp-1.5.0.ipa"' --form 'name="MyRNDemoApp-1.5.0.ipa"'